### ISSUE TITLE
Rendering system

### ISSUE THREAD

**Issue by cmourglia** [Zouch/relwarb#2]
- [ ] Render sprites
    - [x] Still sprite
    - [x] Basic animated sprites (in cycles)
    - [ ] Enhanced animation (transformation, color shifting, group of sprites)
 - [ ] Render text
    - [x] Still text
    - [ ] Animated text (transformation, color shifting, blinking)
 - [ ] More generic //render calls// ?
 - [x] Render queue - Easily queue objects for any frame
 - [ ] Render simple debug primitives (rectangle, circle, etc)
 - [ ] Texture management
    - [ ] Atlas on disc
    - [ ] Atlas on RAM
    - [ ] Atlas on VRAM
