### ISSUE TITLE
Physics system

### ISSUE THREAD

**Issue by cmourglia** [Zouch/relwarb#3]
- [x] Gravity makes stuff fall, characters can jump around
 - [x] Stuff does not go through walls / floors / rough (unless we state otherwise for some reason)
 - [ ] Kaboom baby, attacks affect characters "physically" (impulses FTW)
 - [ ] Environment destruction (if game designer states so)
