### ISSUE TITLE
In game debug system

### ISSUE THREAD

**Issue by cmourglia** [Zouch/relwarb#4]
- [ ] related to #1, might want to log stuff inside the game
 - [ ] basic debug UI (enable / disable visualization of stuff, etc)
 - [ ] basic debug console (related to the one above)
 - [ ] performance graphs ?
